spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp_env?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root