
spring:
  datasource:
    db1:
      url: jdbc:mysql://118.89.219.190:3306/temp_env?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: Huangww@211
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      url: jdbc:mysql://118.89.219.190:3306/mysql?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: Huangww@211
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true